export interface PatientData {
    name: string,
    surname: string,
    patronymic: string,
    dateOfBirth: string,
    survey: PatientSurvey
}

export interface PatientSurvey {
    diagnosisForm?: number,
    diagnosisCourse?: number,
    diagnosisRespiratoryFailure?: number,
    diagnosisDegreeOfControl?: number,
    lengthOfIllness?: number,
    immunotherapyMethods: string[],
    pharmacotherapy: string[],
    effectOfTreatmentWithAllergens: number,
    impactOnWorkFunctions: number,
    difficultyBreathing: number,
    wakeUpFrequency: number,
    inhalerUseFrequency: number,
    degreeOfControl: number,
    ageWhenWasDiagnosed: number,
    isFixedRespiratoryTractObstruction: boolean,
    isLateStart: boolean,
    isHardCourse: boolean,
    isThereContactWithAllergens: boolean,
    isPolysensitizationToAllergens: boolean,
    isAllergicPathology: boolean,
    isCorrectInhalationTechnique: boolean,
    isChronicOstructivePulmonaryDisease: boolean,
    isFollowRecommendedMode: boolean,
    isSmoker: boolean,
    isContinueContactWithAllergens: boolean,
    weight: number,
    height: number,
    isAllergenTreatmentBefore: boolean,
    isLateStartTreatmentWithAllergens: boolean,
    isAutoserotherapyPerformedBefore: boolean,
    isVariationInPeakExpiratoryFlowGreater20: boolean,
    isIntercurrentUpperRespiratoryTractInfections: boolean,
    isUndesirableSideEffectsOfDrugs: boolean,
    isNotPrescribedInhaledGlucocorticosteroids: boolean,
    isUsedIneffectiveDosesOfInhaledGlucocorticosteroids: boolean,
    isForgotToTakeMedicationsForTreatment: boolean,
    isSometimesInattentiveToTheHoursOfMedications: boolean,
    isSkipMedicationsIfFeelWell: boolean,
    isMissNextMedicationsIfFeelBad: boolean
}